#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0x00FFFFFF     \
    active_window_border_color   0xFF00FF00     \
    normal_window_border_color   0x00FFFFFF     \
    window_border_width          2              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  15             \
    bottom_padding               15             \
    left_padding                 15             \
    right_padding                15             \
    window_gap                   04             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Karabiner-Elements" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Mail" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Discord" manage=off
yabai -m rule --add app="Installer" manage=off
yabai -m rule --add app="Steam" manage=off
yabai -m rule --add app="Slay the Spire" manage=off
yabai -m rule --add app="DesktopLauncher" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="Godot" title="^RootsStore" manage=off

echo "yabai configuration loaded.."
